name: intrinsicedit
dependencies:
  - python=3.9
  - pip
  - pip:
    - torch==2.8
    - torchvision
    - torchaudio
    - diffusers==0.20.0
    - huggingface-hub==0.25.0
    - gradio==3.50.0
    - imageio==2.37.0
    - numpy==1.26.4
    - opencv-python
    - transformers
    - wandb==0.21.1
    - lpips==0.1.4
    - h5py==3.14.0
    - markupsafe==2.0.1
    - accelerate==1.10.0
